# -*- coding:utf-8 -*-

SHOW_COMPANY_COLUMN = (
    'updated', 'created', 'StoreName', 'Address', 'License', 'Registrant', 'RegisterTime', 'Telephone', 'F2SAmount',
    'Range', 'Province', 'City', 'County', 'DBName', 'DataTime',)
COMPANY_FIELD = {
    'ID': '编号',
    'Guid': 'Guid',
    'DataTime': '创建时间',
    'DBName': '数据库',
    'StoreName': '公司名称',
    'Address': '店铺地址',
    'License': '营业执照',
    'Registrant': '注册人',
    'Telephone': '手机号码',
    'Province': '省份',
    'City': '城市',
    'County': '区县',
    'RegisterTime': '注册时间',
    'Range': '经营范围',
    'F2SAmount': 'F2S金额',
    'created': '上传时间',
    'updated': '更新时间',
}

SHOW_CAR_COLUMN = (
    'updated', 'created', 'DataTime', 'CarNum', 'VIN', 'Name', 'ContactInfo', 'License', 'BranchStore', 'DriveNoImgOne',
    'OtherImgFour', 'TransmissionNum', 'InsuranceRemindState', 'YearlyinspectionAutoSend',
    'YearlyinspectionRemindSendDate', 'InsuranceRemindDate', 'NameThree', 'Color', 'InsuranceCompany', 'CarStyle',
    'InsuranceAutoSend', 'NameSecond', 'CurrentMileage', 'ColorNum', 'CID', 'OtherImgFive', 'InsuranceDate',
    'YearlyinspectionRemindDate', 'CIDSecond', 'Price', 'OtherImgThree', 'InsuranceRemindSendDate', 'DriveNoImgTwo',
    'CarSery', 'CarBrand', 'CIDThree', 'ChassisNum', 'EngineNumber', 'ExpiryDate', 'CarStyleID', 'Remark',
    'YearlyinspectionRemindState', 'InsuranceAmount')
CAR_FIELD = {
    'updated': '更新时间',
    'created': '上传时间',
    'License': '营业执照',
    'ID': '编号',
    'Guid': 'Guid',
    'VIN': '车架号',
    'DataTime': '创建时间',
    'CarNum': '车牌号',
    'CarStyleID': '车型ID',
    'CarBrand': '车辆品牌',
    'CarSery': '车系',
    'CarStyle': '车型',
    'Price': '车价',
    'Color': '颜色',
    'EngineNumber': '发动机号',
    'CurrentMileage': '当前里程',
    'Name': '车主姓名（默认车主）',
    'CID': '车主ID（默认车主）',
    'ContactInfo': '联系方式',
    'ExpiryDate': '年检到期日',
    'BranchStore': '所属分店',
    'InsuranceCompany': '保险公司',
    'InsuranceAmount': '投保金额',
    'InsuranceDate': '保险到期日',
    'NameSecond': '车主二',
    'CIDSecond': '车主二ID',
    'NameThree': '车主三',
    'CIDThree': '车主三ID',
    'InsuranceRemindDate': '保险提醒时间',
    'InsuranceRemindSendDate': '保险推送时间',
    'InsuranceRemindState': '保险是否推送',
    'InsuranceAutoSend': '保险是否自动推送',
    'YearlyinspectionRemindDate': '年检提醒时间',
    'YearlyinspectionRemindSendDate': '年检推送时间',
    'YearlyinspectionRemindState': '年检是否推送',
    'YearlyinspectionAutoSend': '年检是否自动推送',
    'DriveNoImgOne': '图片一',
    'DriveNoImgTwo': '图片二',
    'OtherImgThree': '图片三',
    'OtherImgFour': '图片四',
    'OtherImgFive': '图片五',
    'Remark': '备注',
    'ColorNum': '色号',
    'ChassisNum': '底盘号',
    'TransmissionNum': '变速箱号',
}

SHOW_CAROWNER_COLUMN = (
    'updated', 'created', 'DataTime', 'Name', 'DriveNo', 'Phone', 'ZPhone', 'Sex', 'Address', 'UnitCustomer',
    'License', 'Remark', 'DriveAutoSend', 'DriveRemindDate', 'DriveNoImgOne', 'ExplainsCustomer', 'CarID', 'AppID',
    'CarCardTwo', 'WeixinState', 'Reference', 'JackpotSpendAmount', 'CarBrand', 'ReferenceID',
    'GradeExpireForever', 'Amount', 'FreeSMSCount', 'Tab', 'CarStyle', 'SpendPwd', 'DriveFractionRemindDate',
    'FractionState', 'CarCardThree', 'CarCard', 'Color', 'CusStaffID','Reward', 'JackpotSpendMuch', 'CarIDTwo',
    'GradeExpireDate', 'LatelySpendDataTime', 'DriveRemindState', 'DriveNoImgTwo', 'DriveFractionRemindDateTime',
    'DriveRemindSendDate', 'DriveEndTime', 'CarSery', 'Birthday', 'Stype',
    'CusStaff', 'ClubCard', 'ClubGrade', 'CarIDThree', 'SID', 'AllowCar', 'ClubGradeID', 'WeChatNo',
    'StypeInCode', 'ExplainsCustomerID', 'NoAmount', 'StoreReward')
CAROWNER_FIELD = {
    'ID': '编号',
    'Guid': 'Guid',
    'updated': '更新时间',
    'created': '上传时间',
    'DataTime': '创建时间',
    'Name': '名称',
    'Sex': '性别',
    'Phone': '手机',
    'CarCard': '车牌',
    'Address': '地址',
    'License': '营业执照',
    'SID': '类别ID',
    'Stype': '类别名称',
    'StypeInCode': '类别内码',
    'WeixinState': '绑定状态',
    'WeChatNo': '微信号',
    'CusStaff': '客服人员',
    'CusStaffID': '客服人员ID',
    'DriveNo': '驾驶证号',
    'DriveEndTime': '驾驶证到期日期',
    'SpendPwd': '消费密码',
    'Birthday': '生日',
    'Reward': '平台积分',
    'Remark': '备注',
    'AppID': '是否绑定App',
    'UnitCustomer': '单位客户',
    'ZPhone': '座机',
    'DriveNoImgOne': '图片一',
    'DriveNoImgTwo': '图片二',
    'CarID': '车辆ID',
    'CarStyle': '车型',
    'CarBrand': '车辆品牌',
    'CarSery': '车系',
    'Color': '颜色',
    'AllowCar': '允许增加车辆',
    'ExplainsCustomerID': '转介绍客户ID',
    'ExplainsCustomer': '转介绍客户',
    'ClubCard': '会员卡号',
    'ClubGrade': '会员等级',
    'ClubGradeID': '会员等级ID',
    'StoreReward': '店面积分',
    'Amount': '余额',
    'NoAmount': '未结算金额',
    'Reference': '推荐人',
    'ReferenceID': '推荐人ID',
    'LatelySpendDataTime': '最近消费时间',
    'JackpotSpendAmount': '累计消费金额',
    'JackpotSpendMuch': '累计消费次数',
    'Tab': '标签',
    'DriveRemindDate': '驾照提醒时间',
    'DriveRemindSendDate': '驾照推送时间',
    'DriveRemindState': '驾照是否推送',
    'DriveAutoSend': '驾照是否自动推送',
    'CarIDTwo': '车辆二ID',
    'CarCardTwo': '车辆二车牌',
    'CarIDThree': '车辆三ID',
    'CarCardThree': '车辆三车牌',
    'FractionState': '分数状态',
    'DriveFractionRemindDateTime': '驾照分数到期提醒时间',
    'DriveFractionRemindDate': '驾照分数提醒时间',
    'GradeExpireDate': '等级到期日',
    'GradeExpireForever': '等级到期永久',
    'FreeSMSCount': '免费短信已发送条数',
}

SHOW_CUSTOMERCONSUME_COLUMN = (
    'updated', 'created',  'ConsumeCarNum', 'CarOwnerName', 'ConsumeContent', 'State', 'GetInTime', 'GetOutTime',
    'GetInMileage', 'ReceivementTime', 'InitialMoney', 'TotalMoney', 'License', 'DataTime', 'OrderTime',
    'ArticleSalesManName', 'ConstructionID',  'EmployeeID',    'StationName', 'ProductSalesManName',  'CreateTime',
    'ConstructionName',   'StationID', 'ProductSalesManID', 'CustomerConsumeNum', 'RedConsumeNum',    'ConsumeCarID',
    'OrderRemark', 'PriorScrapState', 'ScrapTime', 'InsuranceID', 'ArticleConstructorName', 'ArticleConstructorID',
    'CarOwnerID',    'GetOutMileage', 'Stemfrom', 'ArticleSalesManID', 'EmployeeName',  'IntelligentPeccancyQueryNum',
    'BranchStoreID', 'UserRemark', 'InsuranceName', )
CUSTOMER_CONSUME_FIELD = {
    'ID': '编号',
    'Guid': 'Guid',
    'updated': '更新时间',
    'created': '上传时间',
    'CarOwnerName': '车主名称',
    'ConsumeCarNum': '消费车辆车牌号',
    'ConsumeContent': '消费内容',
    'InitialMoney': '统计总金额（未抹零前金额）',
    'TotalMoney': '总金额（实际售价）',
    'ReceivementTime': '收款时间',
    'State': '单据状态',
    'GetInTime': '进场时间',
    'GetOutTime': '出场时间',
    'GetInMileage': '进场里程',
    'GetOutMileage': '出场里程',
    'License': '营业执照',
    'DataTime': '创建时间',
    'CustomerConsumeNum': '客户销售单号',
    'CarOwnerID': '车主ID',
    'ConsumeCarID': '消费车辆ID',
    'ProductSalesManID': '商品销售人员ID',
    'ProductSalesManName': '商品销售人员姓名',
    'ArticleSalesManID': '服务销售人员ID',
    'ArticleSalesManName': '服务销售人员姓名',
    'ArticleConstructorID': '服务施工人员ID',
    'ArticleConstructorName': '服务施工人员姓名',
    'OrderRemark': '单据备注',
    'UserRemark': '用户备注',
    'EmployeeID': '制单人员ID',
    'EmployeeName': '制单人员姓名',
    'OrderTime': '单据日期',
    'CreateTime': '制单时间',
    'BranchStoreID': '分店ID',
    'StationID': '工位ID',
    'StationName': '工位名称',
    'InsuranceID': '保险公司ID',
    'InsuranceName': '保险公司名称',
    'ConstructionID': '施工班组ID',
    'ConstructionName': '施工班组名称',
    'PriorScrapState': '报废前的单据状态',
    'RedConsumeNum': '红冲单编号',  # “完成”状态单据报废时有对应的“红冲”单
    'ScrapTime': '报废时间',
    'Stemfrom': '订单来源',
    'IntelligentPeccancyQueryNum': '对应的智能单单号',
}

SHOW_CUSTOMERCONSUME_DETAIL_COLUMN = (
    'updated', 'created', 'ObjectType', 'ObjectID', 'ObjectName', 'DetailType', 'Discount', 'TotalPrice', 'StockName',
    'StockID', 'License', 'CarOwnerPackagesID', 'CustomerConsumeID', 'Brand', 'Spec', 'DataTime', 'CustomerConsumeNum',
    'BranchStoreID', 'UnitPrice', 'Qty', 'Fit', 'Frequency', )
CUSTOMER_CONSUME_DETAIL_FIELD = {
    'ID': '编号',
    'Guid': 'Guid',
    'updated': '更新时间',
    'created': '上传时间',
    'DataTime': '创建时间',
    'ObjectType': '明细类型',  # 1.商品Product 2.项目Article
    'ObjectID': '商品ID/项目ID',
    'ObjectName': '商品名称/项目名称',
    'License': '营业执照',
    'CustomerConsumeID': '客户销售单号ID(即主表ID)',
    'CustomerConsumeNum': '客户销售单号',
    'Brand': '品牌',
    'Fit': '型号',
    'Spec': '规格',
    'StockID': '出货仓库ID',
    'StockName': '出货仓库',
    'UnitPrice': '单价',
    'Qty': '数量',
    'Discount': '折扣',
    'TotalPrice': '总金额',
    'Frequency': '二次消费（提醒周期）',
    'DetailType': '明细类别',  # 1.已购 2.赠送 3.本店卡券  4.跨店卡券
    'CarOwnerPackagesID': '车主已购套餐明细的ID',  # （如果是已购的，则记录该明细在车主已购套餐明细中的ID）
    'BranchStoreID': '分店ID',
}

SHOW_STD_DATA_COLUMN = (
    'updated', 'created', 'plateNo', 'engineNo', 'statementNo', 'settlementDate', 'deliveryDate', 'deliveryMileage',
    'description', 'repairItems', 'repairParts', 'others', 'sum', 'QAInfo', 'VINCode', 'vehicleOwner', 'vehicleBrand',
    'vehicleType', 'repairType', 'repairName', 'repairMobile', 'source', 'status', 'integratedRate', 'companyId',
    'xlsxPath', 'originalXLSXName', 'xlsxStatus', 'factoryDate', 'factoryMileage',
    'is_status_fix', 'store')

STANDARD_DATA_FIELD = {
    'plateNo': '车牌号码',
    'engineNo': '发动机号码',
    'statementNo': '结算清单编号',
    'settlementDate': '结算日期',
    'deliveryDate': '送修日期',
    'deliveryMileage': '送修里程',
    'description': '故障信息',
    'repairItems': '维修项目列表',
    'repairParts': '维修配件列表',
    'others': '其他费用列表',
    'sum': '总费用',
    'QAInfo': '质保信息',
    'VINCode': 'VIN码',
    'vehicleOwner': '车辆所有者',
    'vehicleBrand': '车辆品牌',
    'vehicleType': '车辆类型',
    'repairType': '维修类型',
    'repairName': '送修人名称',
    'repairMobile': '送修人联系方式',
    'source': '维修表单来源',
    'status': '维修表单是否同步',
    'integratedRate': '表单完整率',
    'companyId': '维修企业',
    'xlsxPath': ' XLSX文件下载',
    'originalXLSXName': '原xlsx名称',
    'xlsxStatus': '数据标准化',
    'factoryDate': '出厂日期',
    'factoryMileage': '出厂里程',
    'updated': '更新日期',
    'created': '创建日期',
    'is_status_fix': '非标准数据',
    'store': '关联对应门店',
}